<Project Sdk="Aspire.AppHost.Sdk/13.4.4">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UserSecretsId>cbf0e576-8eb1-4a99-9b51-346135aaf9a3</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.DevTunnels" Version="13.4.4" />
		<PackageReference Include="Aspire.Hosting.EntityFrameworkCore" Version="13.4.5-preview.1.26316.12" />
		<PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.4" />
		<PackageReference Include="Aspire.Hosting.Kafka" Version="13.4.4" />
		<PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
		<PackageReference Include="Aspire.Hosting.SqlServer" Version="13.4.5" />
		<PackageReference Include="CommunityToolkit.Aspire.Hosting.Minio" Version="13.4.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Instafake.BFF\Instafake.BFF.csproj" />
		<ProjectReference Include="..\Instafake.IdentityEventsIngress\Instafake.IdentityEventsIngress.csproj" />
		<ProjectReference Include="..\Instafake.Multimedia\Instafake.Multimedia.csproj" />
		<ProjectReference Include="..\Instafake.Posts.Api\Instafake.Posts.Api.csproj" />
		<ProjectReference Include="..\Instafake.Posts.Infrastructure\Instafake.Posts.Infrastructure.csproj" IsAspireProjectResource="false" />
		<ProjectReference Include="..\Instafake.Profiles.Api\Instafake.Profiles.Api.csproj" />
	</ItemGroup>

</Project>
