// <auto-generated />
using Instafake.Profiles.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Instafake.Profiles.Infrastructure.Migrations.Profiles
{
    [DbContext(typeof(ProfilesDbContext))]
    partial class ProfilesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Instafake.Profiles.Infrastructure.Entities.Follow", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("text");

                    b.Property<int>("BucketId")
                        .HasColumnType("integer");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint");

                    b.Property<string>("FollowerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProfileId", "BucketId", "Seq");

                    b.HasIndex("ProfileId", "FollowerId")
                        .IsUnique();

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("Instafake.Profiles.Infrastructure.Entities.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FollowersCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PostsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Instafake.Profiles.Infrastructure.Entities.ProfileCounter", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("text");

                    b.Property<long>("NextSeq")
                        .HasColumnType("bigint");

                    b.HasKey("ProfileId");

                    b.ToTable("ProfileCounters");
                });

            modelBuilder.Entity("Instafake.Profiles.Infrastructure.Entities.Follow", b =>
                {
                    b.HasOne("Instafake.Profiles.Infrastructure.Entities.Profile", "Profile")
                        .WithMany("Follows")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Instafake.Profiles.Infrastructure.Entities.ProfileCounter", b =>
                {
                    b.HasOne("Instafake.Profiles.Infrastructure.Entities.Profile", "Profile")
                        .WithOne("ProfileCounter")
                        .HasForeignKey("Instafake.Profiles.Infrastructure.Entities.ProfileCounter", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Instafake.Profiles.Infrastructure.Entities.Profile", b =>
                {
                    b.Navigation("Follows");

                    b.Navigation("ProfileCounter")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
