using Instafake.Profiles.Infrastructure.DbContexts.Config;
using Instafake.Profiles.Infrastructure.Entities;
using Microsoft.EntityFrameworkCore;

namespace Instafake.Profiles.Infrastructure.DbContexts;

// TODO: Raw SQL migrations (or some db integration nuget?) are needed to work efficiently with distributed sql databases
// Currently, the migrations are generated by EF Core and are not suitable for distributed databases. For example, normal B-tree will be used instead of proper partitioning
public class ProfilesDbContext(DbContextOptions<ProfilesDbContext> options) : DbContext(options)
{
    public DbSet<Profile> Profiles => Set<Profile>();
    public DbSet<Follow> Follows => Set<Follow>();
    public DbSet<ProfileCounter> ProfileCounters => Set<ProfileCounter>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .ApplyConfiguration(new ProfileConfiguration())
            .ApplyConfiguration(new FollowConfiguration())
            .ApplyConfiguration(new ProfileCounterConfiguration());
    }
}
