<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>1.0.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentResults" Version="4.0.0" />
		<PackageReference Include="MediatR" Version="14.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Instafake.BuildingBlocks.Domain\Instafake.BuildingBlocks.Domain.csproj" />
	</ItemGroup>

</Project>
